# Generated
background #080B08
foreground #DDF0B0
selection_background #B4FF00
selection_foreground #080B08
cursor #B4FF00
active_tab_foreground #080B08
active_tab_background #B4FF00
inactive_tab_foreground #EAFF00
inactive_tab_background #080B08
tab_bar_background #080B08
color0 #0C110A
color1 #FF3B1A
color2 #39FF14
color3 #EAFF00
color4 #2BD6A0
color5 #FF7518
color6 #4DFFC0
color7 #C8CDC8
color8 #4A5540
color9 #FF3B1A
color10 #39FF14
color11 #DDF0B0
color12 #2BD6A0
color13 #FF7518
color14 #4DFFC0
color15 #F0FFD8
