# Generated
background #151515
foreground #f3ecd4
selection_background #AAD71E
selection_foreground #151515
cursor #AAD71E
active_tab_foreground #151515
active_tab_background #AAD71E
inactive_tab_foreground #fbcb97
inactive_tab_background #151515
tab_bar_background #151515
color0 #1c1c1c
color1 #96333E
color2 #1ed759
color3 #E8E53F
color4 #AAD71E
color5 #F7882D
color6 #90C722
color7 #c1c1c1
color8 #404040
color9 #1ed759
color10 #fbcb97
color11 #f3ecd4
color12 #AAD71E
color13 #F7882D
color14 #90C722
