# Generated
background #111314
foreground #EBD39D
selection_background #AAD71E
selection_foreground #111314
cursor #AAD71E
active_tab_foreground #111314
active_tab_background #AAD71E
inactive_tab_foreground #D9AB77
inactive_tab_background #111314
tab_bar_background #111314
color0 #1A1C1D
color1 #8B3E2F
color2 #9CA84E
color3 #D9AB77
color4 #4E7DA8
color5 #8B4EA8
color6 #4EA8A8
color7 #798581
color8 #44484A
color9 #AAD71E
color10 #798581
color11 #D9AB77
color12 #4E7DA8
color13 #8B4EA8
color14 #4EA8A8
color15 #EBD39D
