color0 #231e1a
color1 #cf767c
color2 #9aa887
color3 #e5c799
color4 #b5a895
color5 #cbaba0
color6 #96b3aa
color7 #dcd8cd
color8 #3a3028
color9 #e09fa4
color10 #b3c2a2
color11 #f0dbb7
color12 #ccbfae
color13 #dec7be
color14 #b1ccc4
color15 #f4f0e6

cursor                #f4f0e6
cursor_text_color     #231e1a
background            #161311
foreground            #dcd8cd
selection_foreground  #3a3028
selection_background  #f4f0e6
active_border_color   #e5c799
inactive_border_color #231e1a
url_color             #e5c799

active_tab_foreground   #161311
active_tab_background   #e5c799
inactive_tab_foreground #bfae9b
inactive_tab_background #231e1a
cursor_trail_color      #bfae9b
