color0 #222222
color1 #aa4444
color2 #338833
color3 #bbbb55
color4 #3377bb
color5 #bb33bb
color6 #33aaaa
color7 #dddddd
color8 #333333
color9 #cc5555
color10 #33aa33
color11 #dddd55
color12 #3377ff
color13 #dd33dd
color14 #33cccc
color15 #ffffff

cursor                #b2b2b2
cursor_text_color     #111111
background            #111111
foreground            #b2b2b2
selection_foreground  #111111
selection_background  #b2b2b2
active_border_color   #b2b2b2
inactive_border_color #222222
url_color             #b2b2b2

active_tab_foreground   #333333
active_tab_background   #b2b2b2
inactive_tab_foreground #dddddd
inactive_tab_background #222222
cursor_trail_color      #dddddd
