"$schema" = 'https://starship.rs/config-schema.json'
right_format = """
[](yellow)\
$cmd_duration\
[](fg:yellow)"""

format = """
[](blue)\
$time\
[](bg:black fg:blue)\
$memory_usage\
${custom.sol-nix}\
[](bg:blue fg:black)\
$git_branch\
$git_status\
[](bg:black fg:blue)\
$python\
$golang\
$nodejs\
$docker_context\
[ ](fg:black)\
$line_break
$directory\
$character"""

palette = 'current'

[directory]
style = "fg:white"
format = "  $path "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:blue"
format = '[[ $symbol $branch ](fg:black bg:blue)]($style)'

[git_status]
style = "bg:blue"
format = '[[($all_status$ahead_behind )](fg:black bg:blue)]($style)'

[nodejs]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:white bg:black)]($style)'

[golang]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version) ](fg:white bg:black)]($style)'

[python]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $version)(\(#$virtualenv\)) ](fg:white bg:black)]($style)'

[docker_context]
symbol = ""
style = "bg:black"
format = '[[ $symbol( $context) ](fg:white bg:black)]($style)'

[memory_usage]
symbol = "󰘚"
threshold = -1
style = "bg:black fg:white"
format = "[ ($symbol:$ram_pct) ]($style)"
disabled = false

[custom.sol-nix]
when = 'env SOL-NIX-ENV'
command = """
CONTRACT_COUNT=$(find . -name "*.sol" 2>/dev/null | wc -l)
if (( CONTRACT_COUNT < 1 )); then
  CONTRACT_COUNT="Null"
fi
SOLC_VER="ERROR"
if command -v solc &>/dev/null; then
  SOLC_VER=$(solc --version | grep -oE '[0-9.]+' | head -n 1)
  echo "◇ ⟠ solc:$SOLC_VER | contracts: $CONTRACT_COUNT ⟠ ◇"
fi
"""
style = "bg:black fg:white"
format = "[$output]($style)"

[time]
disabled = false
time_format = "%I:%M%p"
style = "bg:blue"
format = '[[  $time ](fg:black bg:blue)]($style)'

[line_break]
disabled = true

[character]
disabled = false
success_symbol = '[❯](bold fg:yellow)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:yellow)'
vimcmd_replace_one_symbol = '[❮](bold fg:blue)'
vimcmd_replace_symbol = '[❮](bold fg:blue)'
vimcmd_visual_symbol = '[❮](bold fg:white)'

[cmd_duration]
show_milliseconds = true
format = "[ in $duration]($style)"
style = "bg:yellow fg:black"
disabled = false
show_notifications = true
min_time_to_notify = 45000

[palettes.current]
black = "#080B08"
red = "#FF3B1A"
green = "#39FF14"
yellow = "#B4FF00"
blue = "#EAFF00"
magenta = "#FF7518"
cyan = "#4DFFC0"
white = "#DDF0B0"
