# Generated
general {
    col.active_border = rgba(AAD71E77)
    col.inactive_border = rgba(fbcb9755)
}
misc { background_color = rgba(151515FF) }
plugin {
    hyprbars {
        bar_color = rgba(151515FF)
        col.text = rgba(f3ecd4FF)
    }
}
