# Generated
general {
    col.active_border = rgba(B4FF0077)
    col.inactive_border = rgba(EAFF0055)
}
misc { background_color = rgba(080B08FF) }
plugin {
    hyprbars {
        bar_color = rgba(080B08FF)
        col.text = rgba(DDF0B0FF)
    }
}
