# Generated
general {
    col.active_border = rgba(AAD71E77)
    col.inactive_border = rgba(D9AB7755)
}
misc { background_color = rgba(111314FF) }
plugin {
    hyprbars {
        bar_color = rgba(111314FF)
        col.text = rgba(EBD39DFF)
    }
}
