# Quake terminal configuration (Kitty)
exec-once = [workspace special:quake silent] uwsm app -- kitty --single-instance --class quake

# Keybinds
bind = Super, RETURN, exec, ~/.config/hypr/quake/quake_toggle.sh
bind = Super SHIFT, RETURN, exec, ~/.config/hypr/quake/quake_toggle.sh move
bind = Super ALT, RETURN, exec, ~/.config/hypr/quake/quake_toggle.sh full

# One-liner modern syntax with match:class
windowrule = float on, opacity 1 override 0.95 override, animation slidevert, border_size 0, match:class ^(quake)$
windowrule = rounding 10, border_color rgba(e05f65ff) rgba(111111ff) 45deg, workspace special:quake, match:class ^(quake)$
